server:
  hostname: NODE_SERVER_HOSTNAME
  timeout:  NODE_SERVER_TIMEOUT
  port:  NODE_SERVER_PORT
application:
  debug: NODE_APPLICATION_DEBUG
endpoints:
  listAllBreeds: NODE_ENDPOINTS_ALL_BREEDS
    
